### ISSUE TITLE
inconsistency in dtype member functions

### ISSUE THREAD

**Issue by foucar** [European-XFEL/karabo-bridge-cpp#2]
There is an inconsistency in the dtype() member functions of  karabo_bridge::Object and 
karabo_bridge::Array classes.
Object is returning an int which needs to passed to 
object_type to get a string, whereas Array returns a string.
Next to this, the string inside the object_type is e.g.: uint64_t, whereas the 
arrays dtype would give uint64. I guess the latter is due to the fact that it just takes what python provides.

I think this should be made more consistent by letting both member
functions return either a string (where one either has the _t appended for karabo_bridge::Array::dtype() or removed for karabo_bridge::Object::dtype()) 
or an int pointing to the right entry in object_type.

**Comment by zhujun98** [comment]
The feature has been implemented and tested.
