### ISSUE TITLE
Multiple data source

### ISSUE THREAD

**Issue by tmichela** [European-XFEL/karabo-bridge-cpp#3]
It seems that you are parsing the incoming multipart message in a single kb_data object.
What happens if the message holds several data sources?
example: by getting data from 2 cameras, you would get 2 data source. in the python client, it would be like:
data = {'camera1:output': {'data.image': <ndarray object>, ...}, 'camera2:output': {'data.image': <ndarray object>, ...}}
should be provide a similar container to the user when calling `next`? for example a std::map with first element is a string (source name) and the second is the kb_data object.

**Comment by zhujun98** [comment]
Thank you for pointing it out. I did not realize there exist the case with multiple data sources. I agree to use a std::map as the container to hold data from different sources.
